apiVersion: v1
kind: Service
metadata:
  name: app-machine-learning-be
spec:
  selector:
    app: app-machine-learning-be
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
